language: java
sudo: false

jdk:
  - oraclejdk7

install: true
script:
  - mvn verify -B -e -V

matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
